trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  workerType: standard
  parameterServerType: standard
  workerCount: 0
  parameterServerCount: 0
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: rmse
    maxTrials: 20
    maxParallelTrials: 2
    enableTrialEarlyStopping: True
    params:
      - parameterName: lr
        type: DOUBLE
        minValue: 0.00001
        maxValue: 0.1
        scaleType: UNIT_LOG_SCALE
      - parameterName: dim
        type: DISCRETE
        discreteValues:
          - 2
          - 3
          - 5
          - 10
